steps:
- name: node:18.13.0
  entrypoint: yarn
  args: ["install"]
- name: node:18.13.0
  entrypoint: yarn
  args: ["run", "build-only"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY